# Generated by Django 5.1 on 2024-08-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
    ]
